server:
  port: 1888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/muchat?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: sky980723
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379
    database: 3
    password:
